apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:      
      - path: /nginx
        backend:
          serviceName: deployment-nginx
          servicePort: 80
